[workspace]
members = [
    "types",
    "config",
    "escrow",              # Module 3
    "voucher_registry",    # Module 4
    # "merchant_registry", # Module 4
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = "26.1"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
